config/routes.rb
Rails.application.routes.draw do
  # get 'actions/index'
  # get 'actions/create'
  # get 'actions/destroy'
  # get 'actions/edit'
  # get 'actions/update'
  # get 'actions/show'
  # get 'users/index'
  # get 'users/show'
  devise_for :users
  root "posts#index"
  resources :posts do 
    resources :actions
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/action.rb
class Action < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post
  validates :action, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :actions
  accepts_nested_attributes_for :actions, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :posts
  has_many :actions
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
  def index
  end

  def create
    @action = @post.action.new(action_params)
  end

  def destroy
  end

  def edit
  end

  def update
  end

  def show
  end

  private
  
  def action_params
    params.require(:action).permit(:action,:status).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
    added_attrs = [ :username, :email, :password, :password_confirmation　]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
    
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @action = Action.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    url = params[:post][:youtube_url]
    url = url.last(11)
    @post.youtube_url = url

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: '投稿が完了しました' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: '投稿が更新されました' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: '投稿が削除されました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body, :youtube_url,actions_attributes:[:action,:status]).merge(user_id: current_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actions/create.html.erb
<h1>Actions#create</h1>
<p>Find me in app/views/actions/create.html.erb</p>

app/views/actions/destroy.html.erb
<h1>Actions#destroy</h1>
<p>Find me in app/views/actions/destroy.html.erb</p>

app/views/actions/edit.html.erb
<h1>Actions#edit</h1>
<p>Find me in app/views/actions/edit.html.erb</p>

app/views/actions/index.html.erb
<h1>Actions#index</h1>
<p>Find me in app/views/actions/index.html.erb</p>

app/views/actions/show.html.erb
<h1>Actions#show</h1>
<p>Find me in app/views/actions/show.html.erb</p>

app/views/actions/update.html.erb
<h1>Actions#update</h1>
<p>Find me in app/views/actions/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sekai</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="/js/summernote.css" rel="stylesheet" type="text/css">
<script src="/js/summernote.min.js"></script>
<script src="/public/js/lang/summernote-ja-JP.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

    <div class = "main">

        <div class = "header">

            <div class = "header__left"><%= link_to "MakeUbetter", root_path, class: "navfont" %></div>


              <div class = "header__right">

                    <ul class = "navul">
                      <li class = "navli"><%=link_to " Home",root_path, class: "navfont"%></li>
                      <% if user_signed_in? %>
                      <li class = "navli"><%= link_to "mypage", user_path(current_user.id), class: "navfont" %></li>
                      <li class = "navli"><%= link_to "log out", destroy_user_session_path, method: :delete, class: "navfont"%></li>
                      <li class = "navli"><%= link_to 'New Post', new_post_path , class: "navfont"%></li>
                      <% else %>
                      <li class = "navli"><%= link_to " sign up", new_user_registration_path, class: "navfont" %></li>
                      <li class = "navli"><%= link_to " sign in", new_user_session_path, class: "navfont"%></li>
                      <%end%>
                    </ul>

                <div id="nav-drawer">
                  <input id="nav-input" type="checkbox" class="nav-unshown">
                    <label id="nav-open" for="nav-input"><span></span></label>
                    <label class="nav-unshown" id="nav-close" for="nav-input"></label>
                        <div id="nav-content">
                          <ul class = "navul2">
                            <li class = "navli2"><%=link_to "Home",root_path, class: "navfont"%></li>
                            <% if user_signed_in? %>
                            <li class = "navli2"><%= link_to "mypage", user_path(current_user.id) , class: "navfont"%></li>
                            <li class = "navli2"><%= link_to "log out", destroy_user_session_path, method: :delete, class: "navfont"%></li>
                            <li class = "navli2"><%= link_to 'New Post', new_post_path, class: "navfont" %></li>
                            <% else %>
                            <li class = "navli2"><%= link_to " sign up", new_user_registration_path , class: "navfont"%></li>
                            <li class = "navli2"><%= link_to " sign in", new_user_session_path, class: "navfont"%></li>
                            <%end%>
                            

                          </ul>
                        </div>
                </div>
              </div>
        </div>
       <div class = "contents">
    <%= yield %>
      </div>
    
      <%# <footer>©︎2020 K.KENTA Allright Reserved.
      </footer> %>

      </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :youtube_url %>
    <%= form.text_field :youtube_url %>
  </div>

  <%= form.fields_for :action do |action| %>
  <div class="field">
   <%= action.label :"アクションプラン" %>
    <%= action.text_field :action %>
  </div>

  <div class="field">
   <%= action.label :status %>
    <%= action.text_field :status %>
  </div>
  <%end%>

  


  <div class="field">
    <%= form.label :"この動画の簡単なまとめ" %>
    <%= form.text_area :body %>
  </div>

  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class = "ad">
  <div class = "ad__explain"　onload="alert('ページの読み込みが完了したよ！');">
     MakeUBetterは</br>日々
     動画や本で学んだことを</br>
     記録できるサービスです
  </div>
</div>

<div class = "mokuji">
  <div class = "mokuji__left">All Posts↓</div>
  <div class = "mokuji__right"><%= link_to 'Make New Post', new_post_path, class: "mokuji__right-in" %></div>
</div>

<div class = "content-big-wrapper">
    <% @posts.each do |post| %>
    <div class = "content-wrapper">
      <div class = "videoandtext">
          <div class = "video">
            <iframe class="videos"  src="https://www.youtube.com/embed/<%=post.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen ></iframe>
          </div>
          <div class = "text">
              <div class = "username">:<%= current_user.username%></div>
              <%# <div class = "postbody"><%= post.actions.action%>
              <div class = "postbody"><%= post.body%></div>
              <div class = "cog">
                <%= link_to 'Show', post %>
                <%= link_to 'Edit', edit_post_path(post) %>
                <%= link_to 'Destroy', post, method: :delete, data: { confirm: '本当に削除しますか?' } %>
              </div>
          </div>
        </div>
      </div>
    <% end %>
    </div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


  



  <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @post.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


<%= @post.body.html_safe %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>